spring:
  messages:
    # 定义国际化文件的文件地址，读取的原则是顺序读取如果存在同名的则读取第一个
    basename: i18n/login,i18n/errorMessage
  cache:
    type: redis
    redis:
      use-key-prefix: true
      cache-null-values: true
      time-to-live: 5s
  servlet:
    # 设置文件上传与下载的文件大小限制
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

  http:
    encoding:
      charset: UTF-8
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    entitymanager:
      packagesToScan: com.futao.springbootdemo.model
    hibernate:
      ddl-auto: update
  #    data:
  #      # 全文检索 elasticsearch
  #      elasticsearch:
  #        cluster-name: elasticsearch-service #节点名称
  #        cluster-nodes: 47.106.247.59:9300 #节点地址
  #        repositories:
  #          enabled: true
  # 数据源
  datasource:
    url: jdbc:mysql://47.106.247.59:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: nobug666
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    filters: stat,wall
    initialSize: 5
    minIdle: 10
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
    logSlowSql: true
  # 格式化返回的Timestamp类型
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis
  redis:
    database: 0
    host: 47.106.247.59
    port: 6379
    password: redisPass123.
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 8
        max-wait:
    timeout: 10s
  thymeleaf:
    cache: true
    prefix:classpath: /templates/
    mode: HTML
  # 发邮件
  mail:
    host: smtp.qq.com
    port: 587
    username: 1185172056@qq.com
    password: security
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
  mvc:
    dispatch-options-request: false
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#      mail:
#        smtp:
#          ssl:
#            enable: true

###producer
#该应用是否启用生产者
rocketmq:
  producer:
    onOff: on
    #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: ${spring.application.name}
    #mq的nameserver地址
    nameServerAddr: 127.0.0.1:9876
    #消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    #发送消息超时时间,默认3000
    sendMsgTimeout: 3000
    #发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 心跳检测时间间隔
    heartbeatBrokerInterval: 30000
    vipChannelEnabled: false
  ###consumer
  ##该应用是否启用消费者
  consumer:
    onOff: on
    groupName: ${spring.application.name}
    #mq的nameserver地址
    nameServerAddr: 127.0.0.1:9876
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topics: register
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1
    reConsumerTimes: 3
    tags: register_email

server:
  port: 8888

# 在控制台打印sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 在线人数缩放比例
onlinePeopleQuantityScale: 2

jianshu:
  id: futaosmile

# 线程池配置
threadpool: {corePoolSize: 10,maxPoolSize: 200,queueCapacity: 10}




debug: true
#logging:
#  file: \User\futao\src\backend\fun\springboot_framework\src\main\log666.log
#  level:
#    root: info
#    org:
#      hibernate:
#        SQL: DEBUG
#        ES_TYPE:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

# [日志打印出来不好看.xml]logback-spring
#log:
#  path: logs


futao:
  # 注册邮件验证码过期时间
  registerMailCodeExpireSecond: 7200
  sessionInvalidateSecond: 86 400

# mybatis-plus插件
mybatis-plus:
  typeAliasesPackage: com.futao.springbootdemo.model.entity
  global-config:
    db-config:
      #      大写
      capital-mode: false
      db-type: mysql
      #      查询的时候并不会带上
      table-prefix: futao_
      table-underline: false