spring:
  profiles:
    active: dev
  application:
    name: springbootdemo

author: futao

logging:
  level:
    #    show sql
    com.futao.springbootdemo.dao: debug
    org.springframework.jdbc.core.JdbcTemplate: debug